import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const About = () => {
  const skills = [
    "HTML", "CSS", "JavaScript", "React", "TypeScript", "Tailwind CSS",
    "Bootstrap", "CSS Grid", "Flexbox", "Vite", "AI Tools", "Responsive Design"
  ];

  return (
    <section id="about" className="py-20 bg-background">
      <div className="container mx-auto px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gradient mb-6">
              About Me
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Passionate about creating exceptional web experiences through code
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <Card className="gradient-card shadow-card hover:shadow-hover transition-smooth">
                <CardContent className="p-8">
                  <h3 className="text-2xl font-semibold mb-6 text-foreground">
                    Experience & Skills
                  </h3>
                  <p className="text-muted-foreground leading-relaxed mb-6">
                    During my recent project work, I have developed and deployed a range of web applications 
                    showcasing both traditional and AI-driven development skills. I began by building 
                    pixel-perfect clones of popular platforms like Maybelline, Zomato, and Dribbble using 
                    HTML and CSS. These projects sharpened my front-end design skills and deepened my 
                    understanding of layout systems and UI structure.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    Expanding beyond code-based development, I explored the power of no-code tools to create 
                    SecondHand, a fully functional, AI-built e-commerce site that promotes sustainability by 
                    enabling users to buy and sell second-hand items. Similarly, I created Essentia, an 
                    elegant e-commerce site for luxury perfumes, built entirely using Vercel's v0 and content 
                    generated by ChatGPT.
                  </p>
                </CardContent>
              </Card>
            </div>

            <div>
              <h3 className="text-2xl font-semibold mb-6 text-foreground">
                Technical Skills
              </h3>
              <div className="flex flex-wrap gap-3 mb-8">
                {skills.map((skill) => (
                  <Badge 
                    key={skill} 
                    variant="secondary" 
                    className="px-4 py-2 bg-accent text-accent-foreground hover:shadow-card transition-smooth"
                  >
                    {skill}
                  </Badge>
                ))}
              </div>
              
              <Card className="gradient-card shadow-card">
                <CardContent className="p-6">
                  <h4 className="text-lg font-semibold mb-3 text-foreground">
                    Current Focus
                  </h4>
                  <p className="text-muted-foreground">
                    I'm currently pursuing my B.Tech in Computer Science & Engineering while 
                    building innovative web applications that combine traditional coding skills 
                    with cutting-edge AI tools for rapid prototyping and deployment.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;